# Generated by Django 6.0.3 on 2026-03-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=100)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.FloatField()),
                ('ratings_count', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('image', models.URLField()),
                ('description', models.TextField()),
                ('tag', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
